### ISSUE TITLE
QML warnings on start

### ISSUE THREAD

**Issue by alkersan** [raspberrypi/rpi-imager#38] opened 2020-03-17 08:06 UTC
A few qml warnings are shown in stdout on program start:
```
qrc:/main.qml:739:13: QML QQuickText: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/main.qml:60:17: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/main.qml:95:17: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
qrc:/main.qml:131:17: QML ColumnLayout: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
```

rpi-imager version: [`v1.2`](https://github.com/raspberrypi/rpi-imager/tree/v1.2)
Qt version: `5.14.1`

**Comment by lurch** [comment] 2020-03-17 10:10
Duplicate of #15 ?

**Comment by alkersan** [comment] 2020-03-17 10:25
Yes, didn't find that one

**Closed** 2020-03-17 10:26 UTC
