### ISSUE TITLE
Option to set a fixed IP address on LAN interface and/or WiFi

### ISSUE THREAD

**Issue by Hans-KK** [raspberrypi/rpi-imager#115] opened 2020-11-09 15:20 UTC
An option to set a fixed IP address on LAN interface and/or WiFi would be nice, thank you.
That combined with a checkbox to add a empty file called ssh on the SD card would a nice thing to have, it will save me some steps in creating a new SD card for my pi's

**Comment by lurch** [comment] 2020-11-09 15:34
Duplicate of #12

**Closed** 2020-11-09 15:34 UTC
