### ISSUE TITLE
[BUG] Error Downloading when writing to image

### ISSUE THREAD

**Issue by BastianZim** [raspberrypi/rpi-imager#782] opened 2024-01-12 16:18 UTC
**Describe the bug**

Download of _RASPBERRY PI OS (LEGACY, 64-BIT) LITE_ fails with `Error downloading: HTTP/2 stream 1 was not closed cleanly: STREAM_CLOSED (err 5) - Server IP: 46.235.230.122`

**To Reproduce**
Include steps to allow us to reproduce the error. Include your host OS, and the version of Raspberry Pi Imager.

- Select RPi 3 as Device
- Select OS
- Select customisation
- Start the process

Version: 1.8.4

**Expected behaviour**

Download is successful

**Screenshots or video**
If applicable, add screenshots or a video to help explain your problem.

<img width="792" alt="Screenshot 2024-01-12 at 11 14 00" src="https://github.com/raspberrypi/rpi-imager/assets/10774221/ac143e43-ae2a-4048-97ae-bf422b32c025">

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14, Windows 11, Ubuntu Server 22.04]

macOS 14.2.1

**The name of the OS you are trying to write**

RASPBERRY PI OS (LEGACY, 64-BIT) LITE

**Are you using OS Customisation?**

Yes

**Additional context**

I successfully downloaded the non-legacy image for a RPi 4.

**Comment by maxnet** [comment] 2024-01-14 20:28
Duplicate of #767

**Closed** 2024-01-14 21:48 UTC
Labels: bug
