### ISSUE TITLE
[BUG] When you choose raspberry pi 3 as a device you cannot choose raspian bookworm

### ISSUE THREAD

**Issue by bartex100** [raspberrypi/rpi-imager#756] opened 2023-12-19 14:10 UTC
When you choose raspberry pi 3 as a device you cannot choose raspian bookworm, however based on my testing it works perfectly fine

**Comment by lurch** [comment] 2023-12-19 15:48
Duplicate of #730 ?

**Comment by tdewey-rpi** [comment] 2023-12-21 16:22
Thanks for the report, @bartex100.

As @lurch has pointed out, this issue has been raised previously in #730, so I'm going to close this one as a Duplicate.

**Closed by tdewey-rpi** 2023-12-21 16:22 UTC
Labels: bug
