### ISSUE TITLE
SSH does not work with ubuntu

### ISSUE THREAD

**Issue by aik** [raspberrypi/rpi-imager#324] opened 2021-12-14 03:54 UTC
I programmed the sd card with ubuntu 2104, crtl-shift-x, ticked ssh and the key, flashed, booted, ssh is running but not accepting the key.
I put the card back to the PC and discovered that "writeable" partition does not have the "pi" user at all and no authorized_key contains anything, I added a key, rebooted, works.

So is the "pi" user and ssh setup only supposed to work with debian? The docs don't seem mention it. Thanks,

**Comment by lurch** [comment] 2021-12-14 09:43
Duplicate of #213 , #286 etc. ?

**Comment by maxnet** [comment] 2021-12-14 10:04
If you compile Imager from git, and "use custom" to select a local Ubuntu server image, you do can customize that now.
(Not the desktop edition)

**Comment by aik** [comment] 2021-12-15 00:30
> Duplicate of #213 , #286 etc. ?

yeah, sorry for the noise.

> If you compile Imager from git, and "use custom" to select a local Ubuntu server image, you do can customize that now. (Not the desktop edition)

ctrl-shift-x works when build from git and the image is local and not downloaded? Or you meant I can change the image myself before telling rpi-imager to write it to the card? If it is that, fixing the image afterwards seems easier (my PC runs fedora anyway).

**Comment by maxnet** [comment] 2021-12-15 00:54
>ctrl-shift-x works when build from git and the image is local and not downloaded?

1) If you download Ubuntu **server** from the Internet manually. E.g. by going to: http://cdimage.ubuntu.com/releases/impish/release/ubuntu-21.10-preinstalled-server-arm64+raspi.img.xz

2) And open that in the latest Imager, you can use advanced settings. It should also show a cog icon on the bottom right that gives you the settings:

![screenshot](https://user-images.githubusercontent.com/1123701/146102534-05ffb90e-34fe-4a01-a109-dd7f3ebb5071.png)

Will not work with images from the repository right now, as the repository files has not been updated yet to flag correctly which operating system supports customization and which does not.
(With local files it attempts to auto-detect).

Also only supports Ubuntu Server, NOT Ubuntu Desktop.

**Comment by guysoft** [comment] 2022-01-11 11:42
Hey, can confirm. 
Thanks for pointing out why it does not work. I kept downloading my custom distros and being surprised that it works but then that it does not work on the official images.

**Comment by cillian64** [comment] 2023-10-19 13:03
Closing as a dupe of #213

**Closed by cillian64** 2023-10-19 13:03 UTC
