### ISSUE TITLE
It would be a good idea to add an option to enable ssh by creating an ssh file after installation is complete.

### ISSUE THREAD

**Issue by darton** [raspberrypi/rpi-imager#127] opened 2020-11-27 11:28 UTC
It would be a good idea to add an option to enable ssh by creating an ssh file after installation is complete.

**Comment by lurch** [comment] 2020-11-27 16:30
Duplicate of many other issues :wink: 
https://github.com/raspberrypi/rpi-imager/search?q=ssh&type=issues

**Comment by darton** [comment] 2020-11-27 22:10
OK

**Closed** 2020-11-27 22:10 UTC
