### ISSUE TITLE
Error downloading: SSL certificate problem: certificate has expired. [BUG]: 

### ISSUE THREAD

**Issue by mrkapqa** [raspberrypi/rpi-imager#827] opened 2024-02-26 14:46 UTC
### What happened?

A bug happened!

tried to image for RPi2 latest raspbian image on MacOS Mojave 10.14
the image would not download instead would give an error message:

![Screenshot 2024-02-26 at 15 45 00](https://github.com/raspberrypi/rpi-imager/assets/12947465/2e7c521d-d50d-44dc-9b2d-a15870a493c4)

### Version

1.8.5 (Default)

### What host operating system were you using?

macOS

### Host OS Version

10.14

### Selected OS

Raspbian 32bit

### Which Raspberry Pi Device are you using?

Raspberry Pi A, B, A+, B+, and Compute Module 1

### What kind of storage device are you using?

microSD Card in an internal reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by lurch** [comment] 2024-02-26 16:18
Duplicate of #661 ?

**Comment by tdewey-rpi** [comment] 2024-02-26 16:23
@mrkapqa Unfortunately, as @lurch points out, this is effectively a duplicate of #661. I am therefore closing this issue for two reasons:

1. It's a duplicate of an already raised issue
2. The already raised issue contains my guidance - essentially, we require macOS 10.15 or later at this time.

**Closed by tdewey-rpi** 2024-02-26 16:23 UTC
Labels: bug
