### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by szafranski** [raspberrypi/rpi-imager#820] opened 2024-02-16 01:37 UTC
I think it would be good idea to add an option to disable USB current check on Raspberry Pi 5 from within Raspberry PI imager, so even during first boot Raspberry would boot normally. Especially when someone is powering the Pi another way.

**Comment by lurch** [comment] 2024-02-16 01:40
Duplicate of #775 ?

**Comment by szafranski** [comment] 2024-02-16 01:43
Possible, sorry

**Closed** 2024-02-16 10:18 UTC
Labels: enhancement
