### ISSUE TITLE
BUG Imager 1.7.2: Recovery card fails "Unable to customize. File config.txt does not exist."

### ISSUE THREAD

**Issue by Martin-HiPi** [raspberrypi/rpi-imager#422] opened 2022-04-11 22:13 UTC
Hi!

I've previously set parameters in the Advanced settings menu. 
I'm creating a Bootloader Recovery card and once the card has been written and verified, the error message "Unable to customize. File 'F:/config.txt' does not exist. The card appears to be otherwise correct.

Windows 10 x64 21H2

Thanks!

**Comment by maxnet** [comment] 2022-04-11 22:50
>I'm creating a Bootloader Recovery card

Is that an entry from the menu, or with "use custom"?

**Comment by Martin-HiPi** [comment] 2022-04-11 22:53
Sorry, I should have mentioned using Misc utility images -> Bootloader -> (SD Card Boot is the one I used)

When using "Custom", I usually uncheck the Advanced options for incompatible images, but using the above option, the Advanced options don't show (no gear icon).

**Comment by MLambi-Dover** [comment] 2022-04-12 12:49
I had the same error, but my SD card came out without even a /boot on it.
I used the Raspberry Pi Imager v1.7.2, choose the default option of Desktop, and added customer settings (hostname, WiFi, ssh, password).

I tried a second time with an SD card that already had the /boot partition, and it worked.  I am thinking that the first time around the partition was not created.

**Comment by lurch** [comment] 2022-04-12 16:14
Related issues: https://github.com/raspberrypi/rpi-imager/search?q=Unable+to+customize&type=issues
(in case anything there helps you track down / eliminate the cause of the issue)

**Comment by maxnet** [comment] 2022-04-12 17:05
>Related issues: https://github.com/raspberrypi/rpi-imager/search?q=Unable+to+customize&type=issues

Are not related issues.
With the other issues the users do want customization to happen, but there is something wrong with writing or mounting the FAT partition.

While with the EEPROM recovery case no customization should be happening. But somehow the code does think it should, and thus expects to find config.txt/cmdline.txt on the boot partition, while those are not present with the EEPROM recovery.bin stuff.

**Comment by lurch** [comment] 2022-04-12 17:54
Sorry @maxnet , I guess I should have clarified that my comment was directed at @MLambi-Dover (who said "and added customer settings").

**Comment by thedevopscoder** [comment] 2022-05-14 16:56
How to resolve the issue.
If failed open disk management and assign the system-boot portion a drive letter. Re-run wizard and this should write with no issues.

The next time Pi Imager runs it will assign a drive.

**Comment by tdewey-rpi** [comment] 2024-02-07 11:14
Excellent sleuthing, @thedevopscoder.

I'm closing this issue, as it's not directly related to the rpi-imager codebase.

**Closed by tdewey-rpi** 2024-02-07 11:14 UTC
