### ISSUE TITLE
WIFI/SSH configuration

### ISSUE THREAD

**Issue by schwa** [raspberrypi/rpi-imager#73] opened 2020-05-26 17:27 UTC
It would be nice if rbi-imager could configure ssh and wifi on a newly burnt sd card.

**Comment by lurch** [comment] 2020-05-26 21:55
Duplicate of #12

**Comment by ghollingworth** [comment] 2020-05-27 05:53
The Raspberry Pi Imager application was designed with simplicity in mind, giving the user the smallest number of choices, in the simplest language possible.

Any request that requires extra 'options' or buttons, or may in any way confuse a beginner will not be implemented.

This functionality could only be implemented by adding extra options to the user interface.

**Closed by ghollingworth** 2020-05-27 05:53 UTC
