### ISSUE TITLE
[BUG]: The password field of Advanced Options requires one extra keystroke than necessary to clear the text

### ISSUE THREAD

**Issue by MattyRad** [raspberrypi/rpi-imager#840] opened 2024-03-21 00:11 UTC
### What happened?

```
rpi-imager version 1.7.2
Repository: https://downloads.raspberrypi.org/os_list_imagingutility_v3.json
```

If you fill in the Password field in the Advanced Options section, it is masked by dots, fair enough.

![Screenshot from 2024-03-20 17-03-57](https://github.com/raspberrypi/rpi-imager/assets/1143595/c2df3d43-6520-4eed-803b-c3216d353023)

However, if I want to update the Password with a completely new string, I have to clear out the dots. Double-clicking on the dots does not cursor highlight all of the password text, so instead I use Ctrl-A to select all text in the field.

![Screenshot from 2024-03-20 17-04-02](https://github.com/raspberrypi/rpi-imager/assets/1143595/fb5f5ad1-b218-46cc-bff0-0745d9fdd289)

The bug is that, when I enter a keystroke, the first keystroke clears out the field first, and is not placed into the field.

![Screenshot from 2024-03-20 17-16-53](https://github.com/raspberrypi/rpi-imager/assets/1143595/a8529c07-13aa-4f61-8fc5-7211f5fccb69)

Meaning that if I type `new-password` without visually confirming a character was entered, the actual password is `ew-password`! So us keyboard-lookers and/or fast-typers could be entering the wrong password. This led to quite a bit of befuddledment on my part.

A "view password" unmask text button would be super helpful, but otherwise if it's possible to have the first-typed character be entered into the field (vs only clearing it out), that would also be helpful.

### Version

< 1.8.0

### What host operating system were you using?

Debian and derivatives (eg Ubuntu)

### Host OS Version

Ubuntu 22.04

### Selected OS

Ubuntu 22.04 Server

### Which Raspberry Pi Device are you using?

Raspberry Pi 3B, 3A+, 3B+, and Compute Module 3, 3+

### What kind of storage device are you using?

microSD Card in an internal reader

### OS Customisation

- [X] Yes, I was using OS Customisation when the bug occurred.

**Comment by lurch** [comment] 2024-03-21 00:33
Sounds like a duplicate of #531 ? Try using a more up-to-date version of RPi Imager https://github.com/raspberrypi/rpi-imager/releases

**Closed** 2024-03-21 01:41 UTC
Labels: bug
