### ISSUE TITLE
[BUG]: Pi 5 Kali Image Download Corrupt

### ISSUE THREAD

**Issue by sam-david** [raspberrypi/rpi-imager#885] opened 2024-06-19 02:14 UTC
### What happened?

I have tried on three separate machines now with fresh Raspberry Pi imager installs and separate sd cards to download and write the Kali image for Raspberry Pi 5. Each time I get a "Download corrupt. Hash does not match" error. I noticed this happened sometime around downloading the latest version but not sure if that is related. Perhaps it has to do with the image being pulled down itself?

![Screenshot 2024-06-07 at 5 42 27 AM](https://github.com/raspberrypi/rpi-imager/assets/7275374/9f2b9fc9-25f6-47fc-8974-12d7ff5d4703)

### Version

1.8.5 (Default)

### What host operating system were you using?

macOS

### Host OS Version

Sonoma 14.3.1

### Selected OS

Kali Linux (Raspberry Pi 5 - 64-bit)

### Which Raspberry Pi Device are you using?

Raspberry Pi 5

### What kind of storage device are you using?

microSD Card in a USB reader

### OS Customisation

- [ ] Yes, I was using OS Customisation when the bug occurred.

**Comment by tdewey-rpi** [comment] 2024-06-19 09:17
I can reproduce this, and will escalate to my point of contact with Kali Linux.

Unfortunately, as this is not an issue with `rpi-imager` itself, I must close this report - but I'll drop another comment once I've had notice from the KL developers they're back in shape.

**Closed by tdewey-rpi** 2024-06-19 09:17 UTC
Labels: bug

**Comment by sam-david** [comment] 2024-06-19 10:44
Thanks @tdewey-rpi! I was able to reproduce this on my windows 10 machine with 1.8.5 and even a downgraded version of 1.8.4 so I figured it was the image as well. Please let me know when you hear from them.

**Comment by yetanotherusern4me** [comment] 2024-06-20 01:00
I am having this same issue with raspberry pi 4 image.

**Comment by abheek648** [comment] 2024-07-07 15:31
I have the same problem with kali

**Comment by cxnturi0n** [comment] 2024-07-12 17:36
This is still an Issue. The image seems to be corrupted, from either rpi installer and from https://www.kali.org/get-kali/#kali-arm

**Comment by sam-david** [comment] 2024-07-12 22:13
@tdewey-rpi any updates from the Kali team? 

For anyone else, I got around this by flashing the ARM images directly from Kali at https://www.kali.org/get-kali/#kali-arm

**Comment by abheek648** [comment] 2024-07-13 07:14
@sam-david is the image 64bit or 32bit?

**Comment by andychess** [comment] 2024-07-14 16:43
Hi,
Same problem here.  Both 32 and 64 bit images affected.  It's not only a problem on the Rpi imager, downloading directly from the Kali website also produces the error.

**Comment by sam-david** [comment] 2024-07-15 01:18
> @sam-david is the image 64bit or 32bit?

I understand a lot of you are having issues even with directly from Kali website. However, this worked for me on my Raspberry Pi 5s using the 2024.2 arm64 download.

**Comment by andychess** [comment] 2024-07-15 07:31
I just tried downloading the Pi5 version and can confirm that it is working fine.  The problem seems to be with the 32 and 64 bit  Pi 2, 3, 4, 400 images.

I my case I have tried on Mac / Win using Balena Etcher and the Pi Imager. Using tar, gunzip etc all produce an error.

**Comment by abheek648** [comment] 2024-07-15 16:46
I hope this link helps cuz it helped me  https://www.youtube.com/watch?v=ZzCdfey8abU

**Comment by sam-david** [comment] 2024-07-15 20:42
> I just tried downloading the Pi5 version and can confirm that it is working fine. The problem seems to be with the 32 and 64 bit Pi 2, 3, 4, 400 images.
> 
> I my case I have tried on Mac / Win using Balena Etcher and the Pi Imager. Using tar, gunzip etc all produce an error.

Yes, @andychess makes a good point I forgot to mention. I used Balena Etcher instead of the Pi Imager to flash for the direct kali downloads

**Comment by NenadX** [comment] 2024-07-17 09:17
I also have a problem using dd on Kali Vbox, as well as on the net installation.
![Kali image error](https://github.com/user-attachments/assets/0c3cd90c-1689-4f8d-83ce-dad3cc8cb3f3)
