### ISSUE TITLE
[OS request] Add Kali images

### ISSUE THREAD

**Issue by demosjarco** [raspberrypi/rpi-imager#415] opened 2022-04-08 01:14 UTC
Kali provides their ready to run images [https://www.kali.org/get-kali/#kali-arm](https://www.kali.org/get-kali/#kali-arm).
I've been able to drop these images from their website directly into `rpi-imager` and it bruns them just fine, no additional options/settings/steps needed.

What needs to be done to add this in the menu choices in `rpi-imager`?

**Comment by demosjarco** [comment] 2022-04-08 01:22
Opened matching issue [#279](https://gitlab.com/kalilinux/build-scripts/kali-arm/-/issues/279) on Kali's repo

**Comment by steev** [comment] 2022-08-22 02:57
Hey @demosjarco thanks for opening the issue for us - we'd like to see this too, and we have the bits in place now except for one final part (where we're going to host the json) - but we do want to see this as well.  I've already tested the json file across all the images, and they all write correctly as well as boot (though we have not tested, and do not expect to fully support the advanced menu just yet)

Once we get the json file hosted on our servers, I'll post the link here since I'm not sure if I should open a second issue to request it or not.

**Comment by steev** [comment] 2022-09-05 01:20
@ghollingworth This is now ready - we (Kali) have the json file hosted at https://www.kali.org/rpi-imager.json and this is where it will stay.  We do not (currently) support using the advanced menu options for things like adding a user, but we hope to in the future.  Do you need more information than this?

**Comment by demosjarco** [comment] 2022-09-05 03:58
@ghollingworth Can confirm `rpi-imager --repo https://www.kali.org/rpi-imager.json` works and writes images as expected.
![image](https://user-images.githubusercontent.com/1209494/188357596-9ca08275-f2f3-4d85-9aaf-9da7b3aece83.png)

**Comment by XECDesign** [comment] 2022-09-06 15:36
Could you please provide the snippet you'd like included in https://downloads.raspberrypi.com/os_list_imagingutility_v3.json as well?

**Comment by g0tmi1k** [comment] 2022-09-06 15:46
Sure!
What are the values/fields that need content/populating?

Looking at it, I see:

```json
{
[...]
    "os_list": [
       {
 [...]
            "subitems": [
                {
                    "name": "[...]",
                    "description": "[...]",
                    "icon": "[...]",
                    "subitems_url": "[...]",
                    "website": "[...]"
```

**Comment by XECDesign** [comment] 2022-09-07 15:05
Yeah, all of that. Mainly the website and description, so that I don't need to guess what you'd like there.

**Comment by g0tmi1k** [comment] 2022-09-08 15:59
- Name: `Kali Linux
- Description: `Kali Linux is an open-source, Debian-based Linux distribution geared towards various information security tasks, such as Penetration Testing, Security Research, Computer Forensics and Reverse Engineering.`
- Icon: `https://www.kali.org/images/kali-dragon-icon.svg`
- subitems_url: `https://www.kali.org/rpi-imager.json`
- Website: `https://www.kali.org/`

**Comment by XECDesign** [comment] 2022-09-14 14:03
Seeing a couple of issues with https://kali.download

The main one is that quite often the write appears to hang at x%. Using wget or curl on an image shows an estimated download time of over 4 hours:

```
> wget -O - 'https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz' | xzcat > /dev/null
--2022-09-14 14:48:33--  https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz
Resolving kali.download (kali.download)... 2606:4700::6812:6764, 2606:4700::6812:6664, 104.18.102.100, ...
Connecting to kali.download (kali.download)|2606:4700::6812:6764|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1954745680 (1.8G) [application/octet-stream]
Saving to: ‘STDOUT’

-                                                 3%[==>                                                                                                   ]  58.16M  82.1KB/s    eta 4h 13m 
```

It tends to start out at decent speeds and then settles at 50-150 KB/s

I've tried downloading from different locations to rule out that the problem is with the office network and without using the xzcat to make sure it's not just very slow decompression.

**Comment by g0tmi1k** [comment] 2022-09-14 19:09
We have had a problem with our CDN setup.
Its been a rocky/patchy since 07-09 September, then again 12-14 September 2022.
First set of issues we have had issues since July 2018 when it was initially setup.

I would like to think its "sorted" now.

**Comment by lurch** [comment] 2022-09-14 22:53
I just gave a quick test on my own home cable-internet connection - `wget https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz` started off downloading at about 3 MB/s, then settled down to around 1.5MB/s, occasionally dropping to below 1MB/s. I killed the wget process when it got to 20% (the ETA was still over quarter of an hour).
As a comparison, I also tried `wget https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-07/2022-09-06-raspios-bullseye-arm64.img.xz` and that rattled along at 25MB/s (and completed in well under a minute).

**Comment by steev** [comment] 2022-09-15 01:40
fwiw, here is my same wgets.

```
steev@vincenzo:~/test$ wget https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz
--2022-09-14 20:36:59--  https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz
Resolving kali.download (kali.download)... 104.18.103.100, 104.18.102.100, 2606:4700::6812:6664, ...
Connecting to kali.download (kali.download)|104.18.103.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1954745680 (1.8G) [application/octet-stream]
Saving to: ‘kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz’

kali-linux-2022.3-raspberry-pi-zero-w-pitail- 100%[==============================================================================================>]   1.82G  38.2MB/s    in 51s

2022-09-14 20:37:51 (36.5 MB/s) - ‘kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz’ saved [1954745680/1954745680]

steev@vincenzo:~/test$ wget https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-07/2022-09-06-raspios-bullseye-arm64.img.xz
--2022-09-14 20:38:02--  https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2022-09-07/2022-09-06-raspios-bullseye-arm64.img.xz
Resolving downloads.raspberrypi.org (downloads.raspberrypi.org)... 93.93.135.117, 46.235.231.111, 46.235.230.122, ...
Connecting to downloads.raspberrypi.org (downloads.raspberrypi.org)|93.93.135.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 820254568 (782M) [application/x-xz]
Saving to: ‘2022-09-06-raspios-bullseye-arm64.img.xz’

2022-09-06-raspios-bullseye-arm64.img.xz      100%[==============================================================================================>] 782.25M  18.2MB/s    in 49s

2022-09-14 20:38:51 (16.1 MB/s) - ‘2022-09-06-raspios-bullseye-arm64.img.xz’ saved [820254568/820254568]
```

It's definitely unfortunate that our CDN was having issues, but they *should* be fixed now.

**Comment by maxnet** [comment] 2022-09-15 07:37
Does max out my gigabit link now (99 Mbyte/sec).

```
$ wget -O/dev/null https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz
--2022-09-15 09:34:42--  https://kali.download/arm-images/kali-2022.3/kali-linux-2022.3-raspberry-pi-zero-w-pitail-armel.img.xz
Resolving kali.download (kali.download)... 104.18.103.100, 104.18.102.100, 2606:4700::6812:6764, ...
Connecting to kali.download (kali.download)|104.18.103.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1954745680 (1.8G) [application/octet-stream]
Saving to: '/dev/null'

/dev/null                                    100%[=============================================================================================>]   1.82G  96.9MB/s    in 19s     

2022-09-15 09:35:01 (99.2 MB/s) - '/dev/null' saved [1954745680/1954745680]
```

**Comment by XECDesign** [comment] 2022-09-15 09:40
Thanks. This should be in the other specific purpose operating systems section now.

**Comment by lurch** [comment] 2022-09-15 10:54
FWIW, I'm now getting 25MB/s with the Kali image too; so yup it looks like your CDN problems have been resolved now :+1:

**Comment by g0tmi1k** [comment] 2022-09-15 16:39
@XECDesign Great stuff! Thank you!

For the record, could you share the commit that made it happen?

**Comment by maxnet** [comment] 2022-09-15 16:59
>For the record, could you share the commit that made it happen?

Repository is not hard-coded in Imager, but lives here: https://downloads.raspberrypi.org/os_list_imagingutility_v3.json

**Comment by lurch** [comment] 2022-09-16 08:44
I guess this issue can be closed now?

**Closed** 2022-09-23 01:52 UTC

**Comment by g0tmi1k** [comment] 2022-12-08 11:06
@XECDesign, Sorry for being a pain.
Would it be possible to switch the logo?

We _finally_ have a [press-pack](https://gitlab.com/kalilinux/documentation/press-pack). The idea is to have the same image used throughout. 

I believe it's currently like: <https://www.kali.org/images/kali-dragon-icon.svg>
Could you switch it to be: <https://www.kali.org/images/kali-linux-logo.svg>
_This should match whats on: <https://www.kali.org/rpi-imager.json>_

That way, the menu icon matches all the submenu sections

**Comment by XECDesign** [comment] 2022-12-09 17:35
No pain at all. Should be updated now.
