### ISSUE TITLE
[BUG] Raspberry Pi 3 OS selection only offers Legacy (bullseye) versions

### ISSUE THREAD

**Issue by SkyLined** [raspberrypi/rpi-imager#781] opened 2024-01-10 21:21 UTC
**Describe the bug**
"Raspberry Pi OS" versions based on bookworm appear to run just fine on my Pi 3 but if I try to select them in imager, they are filtered out when I select Pi3 as the target device.

I tested "Raspberry Pi OS (64-bit) Lite" on a "Raspberry Pi 3 Model B Rev 1.2" and it appears to run without any issues.

**To Reproduce**
Under "Raspberry Pi Device", select "Raspberry Pi 3". Under "Operating System", notice that all "Raspberry Pi OS" options are for Legacy (bullseye) versions; none of the bookworm versions are available.

**Expected behaviour**
When selecting Pi 3 for the Device, the Raspberry Pi OS bookworm-based versions should be available.

**Screenshots or video**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 (should be irrelevant)

**The name of the OS you are trying to write**
non-Legacy versions of Raspberry Pi OS

**Are you using OS Customisation?**
N/A

**Additional context**
N/A

**Comment by tdewey-rpi** [comment] 2024-01-12 12:15
@SkyLined Please search the existing issues before raising a new issue.

This is another duplicate of #730

**Closed by tdewey-rpi** 2024-01-12 12:15 UTC
Labels: bug
