### ISSUE TITLE
[Feature Request] Add tick box to enable SSH

### ISSUE THREAD

**Issue by Jake-Barwell** [raspberrypi/rpi-imager#102] opened 2020-08-13 09:53 UTC
With the ability for Raspbian to detect a file in the boot sector and enable ssh, I believe it would be useful for beginners to be able to check a box to have this file automatically included. 

This would simplify the process, mainly on windows where the ability to change a file extension requires changing settings in file explorer. Most new users would most likely not know about this feature anyway, so this checkbox would likely be the first time they encounter SSH on the PI.

**Comment by Jake-Barwell** [comment] 2020-08-13 09:55
another potential use case for this type of customization would be the ability to enter WiFi credentials and have the program compile a WPA supplicant file.

**Comment by ghollingworth** [comment] 2020-08-13 09:59
Duplicate of many others

**Closed by ghollingworth** 2020-08-13 09:59 UTC
