### ISSUE TITLE
Raspberry Pi Imager UI opens with wrong language

### ISSUE THREAD

**Issue by keelaro** [raspberrypi/rpi-imager#160] opened 2021-03-10 17:15 UTC
I have installed the RPi Imager on MacOS Big Sur 11.2.3 and the language that displays is not English even thought this is my default language. 

Having google the issue I saw a suggestion to check the setting i preferences. I noticed that although English is the preferred and default language German and Dutch and Hungarian option were also in my list (there for other purposes). When I delete these from my preference list RPi Imager now opens in English language.

**Comment by maxnet** [comment] 2021-03-10 17:21
Which Imager version are you using?
As this was supposed to be fixed in Imager v1.4

https://github.com/raspberrypi/rpi-imager/issues/81

**Comment by maxnet** [comment] 2021-03-12 16:10
Am afraid I am unable to reproduce the problem.
Only becomes Dutch for me when I drag it to the top in the list of languages.

![Screenshot 2021-03-12 at 16 59 50](https://user-images.githubusercontent.com/1123701/110966602-b52cc100-8355-11eb-8a30-c33bb773ad40.png)

![Schermafbeelding 2021-03-12 om 17 00 22](https://user-images.githubusercontent.com/1123701/110966610-b9f17500-8355-11eb-98da-d1f6076105e7.png)

Using v1.5 from raspberrypi.org

**Comment by maxnet** [comment] 2021-03-26 15:23
@keelaro can you try if this one works better for you?

[Raspberry Pi Imager 1.7.zip](https://github.com/raspberrypi/rpi-imager/files/6212737/Raspberry.Pi.Imager.1.7.zip)

**Comment by maxnet** [comment] 2021-03-29 18:14
Fixed in 1.6.1

**Closed by maxnet** 2021-03-29 18:14 UTC
