### ISSUE TITLE
Wi-Fi Networks with parenthesis

### ISSUE THREAD

**Issue by Anthony6444** [raspberrypi/rpi-imager#509] opened 2022-11-28 03:47 UTC
After installing Rasberry Pi OS Lite (64bit) version 2022-09-22, with a wifi name that has a pair of parenthesis in it, `/boot/firstrun.sh`  fails with the following error:
```
[28.832781] firstrun.sh[276]: /boot/firstrun.sh: line 39: syntax error near unexpected token `)'
[28.834457] firstrun.sh[276]: /boot/firstrun.sh: line 39: `  /usr/lib/raspberrypi-sys-mods/imager_custom set_wlan 'Wifi (Taylor\'s Version)' '8d82....536' 'US'
```
![PXL_20221128_033036155](https://user-images.githubusercontent.com/59541967/204189927-7a0bba9a-6b5f-4669-9d03-65fdba1ee409.jpg)

**Comment by Anthony6444** [comment] 2022-11-28 04:01
reflashing with a different wifi name and booting again solves the issue, but I would really like to see this fixed!

**Comment by maxnet** [comment] 2022-11-28 11:06
Duplicate of #486 and already fixed in git.

**Closed** 2022-11-28 11:07 UTC
