### ISSUE TITLE
Raspberry Pi OS Bookworm absent for Raspberry Pi's 3 and older

### ISSUE THREAD

**Issue by grandsilvergalaxy** [raspberrypi/rpi-imager#690] opened 2023-10-19 23:09 UTC
No Raspberry Pi OS on top
![image](https://github.com/raspberrypi/rpi-imager/assets/93889717/c2627e5c-f890-43ca-9040-de1904d80577)
Raspberry Pi OS (Other Category) No Bookworm
![image](https://github.com/raspberrypi/rpi-imager/assets/93889717/8bc2ede5-91c3-4474-85cb-aec93c2c5a9d)
Affected Models in Selection 1,2,3, and 2w

**Comment by tdewey-rpi** [comment] 2023-10-20 09:34
Thanks for the report, @grandsilvergalaxy.

We're not explicitly recommending Bookworm for Pi3 and older at this time. If you want to write Bookworm, I'd advise you use the 'No filtering' option in the device selector.

Closing, as this is working as intended at this time.

**Closed by tdewey-rpi** 2023-10-20 09:34 UTC

**Comment by b-reich** [comment] 2023-11-04 20:50
![grafik](https://github.com/raspberrypi/rpi-imager/assets/1573025/39d245d9-ff7b-477a-88e2-95d02a4f7789)

this is really confusing
its not listed on the website that it is not recommended
https://www.raspberrypi.com/software/operating-systems/

**Comment by b-reich** [comment] 2023-11-04 20:51
> Thanks for the report, @grandsilvergalaxy.
> 
> We're not explicitly recommending Bookworm for Pi3 and older at this time. If you want to write Bookworm, I'd advise you use the 'No filtering' option in the device selector.
> 
> Closing, as this is working as intended at this time.

![grafik](https://github.com/raspberrypi/rpi-imager/assets/1573025/39d245d9-ff7b-477a-88e2-95d02a4f7789)

this is really confusing
its not listed on the website that it is not recommended. it is even recommended
https://www.raspberrypi.com/software/operating-systems/
