### ISSUE TITLE
[BUG] Imager v. 1.8.5. opens in a blank screen window

### ISSUE THREAD

**Issue by Rhuax** [raspberrypi/rpi-imager#791] opened 2024-01-25 21:14 UTC
I installed version 1.8.5. and whenever I open it I have a completely blank screen window:
![pyhSrOe](https://github.com/raspberrypi/rpi-imager/assets/9083577/3fe89bdc-2eb7-4273-9d37-ecd56baac49c)

**Desktop (please complete the following information):**
 - OS: Windows 7 Home Premium
**Are you using OS Customisation?**
No
**Additional context**
I also tested v. 1.8.4. and it behaves equally

**Comment by Rhuax** [comment] 2024-01-25 21:22
I'm using Imager locally and I do not run (and never did not his PC) any kind of games or other GPU accelerated software.

**Comment by tdewey-rpi** [comment] 2024-01-31 13:28
Thanks for the report, @Rhuax.

Your report made me go digging a little deeper into how Qt falls back from failing to operate OpenGL, and I found something I didn't expect - lots of reports of failure and instability, including on Windows devices that have some form of GPU acceleration but fail to offer something equivalent to OpenGL:ES 2.0 or DirectX 9:

https://stackoverflow.com/questions/27704529/deploying-qt5-on-windows-without-hardware-acceleration

I can't immediately see a good path forward, but I'll try to find some time to look into a more graceful fallback mechanism. In the meantime, depending on your level of comfort, you may want to explore environment variables to force Qt5 to use software rendering.

**Comment by joergschultzelutter** [comment] 2024-06-03 12:41
@tdewey-rpi  - I experienced the same issue on MacOS. You _can_ restore an almost-complete version of the Imager by doing the following things:

- set the QT_QUICK_BACKEND=software environment variable
- then open the Imager via command line by running open Raspberry\ Pi\ Imager.app/

Most of the buttons will still be gone but if you navigate with caution, one can use the Imager for writing images to an SD card. Not sure if there is another env setting which might remove the remaining obstacles.

**Comment by tdewey-rpi** [comment] 2024-06-03 12:50
> @tdewey-rpi - I experienced the same issue on MacOS. You _can_ restore an almost-complete version of the Imager by doing the following things:
> 
> * set the QT_QUICK_BACKEND=software environment variable
> * then open the Imager via command line by running open Raspberry\ Pi\ Imager.app/
> 
> Most of the buttons will still be gone but if you navigate with caution, one can use the Imager for writing images to an SD card. Not sure if there is another env setting which might remove the remaining obstacles.

Thanks for the comment, @joergschultzelutter.

I would indeed expect your workaround to be operational - though I'm surprised you had _any_ rendering issues (as we don't directly drive a 3D API inside the UI).

What's confounding the path forward here is that I would have expected Qt to perform some sort of routine to determine if the host OS was able to support the accelerated backend, and then if that failed, automatically revert to the software backend. That isn't happening - and that isn't something I would generally expect a project like `rpi-imager` to have to deal with, instead relying on the UI toolkit to do, well, UI toolkit things.

**Comment by joergschultzelutter** [comment] 2024-06-03 14:15
Thanks @tdewey-rpi . For illustration purposes - this is the Imager without the env setting:

![Raspberry Pi Imager v1 8 5 2024-06-03 16-10-01](https://github.com/raspberrypi/rpi-imager/assets/76180229/ed2e8c65-c5de-463d-a749-b2be46cc7e17)

And this is how things look like if you set that environment variable:

![Raspberry Pi Imager v1 8 5 2024-06-03 16-12-28](https://github.com/raspberrypi/rpi-imager/assets/76180229/7f05e905-71de-4937-a30a-47efa83f68a3)

As you can see, most of the buttons/dropdowns are no longer visible. Yet, they can still be used if you know where they are located at.

FWIW, I'm running MacOS Sonoma and had never any of these issues prior to the OS update.

**Comment by tdewey-rpi** [comment] 2024-06-03 14:18
@joergschultzelutter Apologies - perhaps I misread - are you seeing this on an Apple-supported macOS device running Sonoma without any exotic configuration?

**Comment by joergschultzelutter** [comment] 2024-06-03 14:27
@tdewey-rpi - I'm running a vanilla version of Sonoma without any exotic kernel extensions etc.

For completeness sake - I had similar issues with this German app: https://apps.apple.com/de/app/ausweisapp-bund/id948660805#?platform=iphone. The symptoms were exactly the same: fortunately, the developers hinted me on setting that environment variable - which then solved the issue. Other reviews on the App store show exactly the same behavior which makes me believe that this is not an isolated issue. As @Rhuax runs the imager on Windows, I have to assume that the issue in question is not related to MacOS.

**Comment by tdewey-rpi** [comment] 2024-06-03 14:56
> @tdewey-rpi - I'm running a vanilla version of Sonoma without any exotic kernel extensions etc.
> 
> For completeness sake - I had similar issues with this German app: https://apps.apple.com/de/app/ausweisapp-bund/id948660805#?platform=iphone. The symptoms were exactly the same: fortunately, the developers hinted me on setting that environment variable - which then solved the issue. Other reviews on the App store show exactly the same behavior which makes me believe that this is not an isolated issue. As @Rhuax runs the imager on Windows, I have to assume that the issue in question is not related to MacOS.

I'm specifically trying to determine if this issue is being reported against a commonly-deployed and currently-supported platform.

I have not had any other reports of a blank screen on Sonoma reported against a currently-supported Apple device, and I would be extremely surprised to encounter a situation where macOS was unable to offer an acceleration-friendly rendering pipeline.

Can you confirm the hardware you're running on?

**Comment by joergschultzelutter** [comment] 2024-06-04 10:34
I just tried to verify the behavior on my workplace Macbook - to no avail. Seems as if the issue is related to my private 2015 MBP (using OCLP).

**Comment by tdewey-rpi** [comment] 2024-06-04 15:32
@joergschultzelutter Thanks for confirming.

Unfortunately OCLP would indeed count as an 'exotic' modification - essentially, you've managed to convince Sonoma to run on hardware Apple do not support it on.

As such, your report matches that of the OP fairly well - a device that is unable to offer a hardware accelerated UI running a program that expected to find one.

As before - there isn't a great path forward here. I'm reticent to commit time to supporting `rpi-imager` on operating systems that the vendor does not support, not least because in the event of an immovable bug we would have no path forward - either in terms of requesting support from Qt or from the OS vendor.

If you still observe this issue on Monterey (macOS 12), I'd consider that a different bug - because it would be a version of macOS running on hardware it claims to support that is still receiving security updates.

**Comment by nfriacowboy** [comment] 2024-06-07 23:29
Just a workaround for those running OCLP, install a Linux distro on a VM and Raspberry Pi Imaginer (v1.8.5) works. (Tested with Pop! on Parallels)

**Comment by staff009** [comment] 2024-06-21 09:06
On Win7 these two environment vars disabled OpenGL and I could use the Raspberry Pi Imager 1.8.5. 

QT_OPENGL = angle
QT_ANGLE_PLATFORM = warp 

from: 
https://raspberrypi.stackexchange.com/questions/137481/how-to-run-raspberry-pi-imager-in-old-windows-computer-without-opengl-2-0-or-wit

**Comment by joergschultzelutter** [comment] 2024-06-21 15:29
@staff009's suggestion improves the situation a little bit; the buttons and dropdowns are still gone, but at least the proper text from the dropdown menu shows up if you know where it is located.

To summarize, my machine's .bash_profile contains 

    export QT_QUICK_BACKEND=software
    export QT_OPENGL=angle
    export QT_ANGLE_PLATFORM=warp

If I open the imager via command line, those settings restore 90% of its functionality. Thanks!

![Raspberry Pi Imager v1 8 5 2024-06-21 17-19-01](https://github.com/raspberrypi/rpi-imager/assets/76180229/bbeced55-f93a-4ab7-8941-a0ce386d77c3)

**Comment by staff009** [comment] 2024-06-23 11:14
@joergschultzelutter, on Win7 with no GPU and a Intel Core Duo T9400 CPU it just looks fine. I had the impression all buttons and dropdown menus seemed genuine.
Without the env vars the imager shows the content of background window, in this case the device manager:
![grafik](https://github.com/raspberrypi/rpi-imager/assets/13884995/3665b720-f6c0-442b-82e1-192af2896c98)

With the env vars, everything OK: 
![grafik](https://github.com/raspberrypi/rpi-imager/assets/13884995/090d8449-e468-40dd-ac60-cd677a79d329)

**Comment by tdewey-rpi** [comment] 2024-06-27 11:25
I must thoroughly applaud you, @joergschultzelutter and @staff009, for identifying a solid workaround.

I can't see a clean way to have Imager automatically make use of this, without having Imager gain some more concrete knowledge of the host operating system. As I've said before, I expected Qt to handle this entirely internally - that it has not is disappointing, but also not entirely unexpected - as Windows 7 is no longer actively supported by the Qt project.

I'm going to do two things from here:

First, I'm going to pin this issue as an excellent example of the community working together to provide a workaround where a code change is impractical.

Second, I'm going to close the issue as `Won't fix`, because I can't see a way to fix it from inside the Imager codebase in a clean manner.

**Closed by tdewey-rpi** 2024-06-27 11:25 UTC
Labels: bug

**Comment by shindekokoro** [comment] 2024-10-26 10:05
This "bug" is present of all 1.8.x releases for macOS Sonoma. Resolution of loading through terminal above does allow some visual functionality. The issue is not present for 1.7.x release

**Comment by lurch** [comment] 2024-10-27 14:05
@shindekokoro What hardware are you running macOS Sonoma on?

**Comment by tdewey-rpi** [comment] 2024-10-28 11:27
Echoing @lurch 's comment, the only macOS systems we have had this reported on are those where the user has circumvented an Apple restriction to run a newer OS on unsupported hardware.

I can confirm from my own testing that v1.8.5 renders and works correctly on Sonoma on a macBook Pro M1 (2021).
