### ISSUE TITLE
Imager on macOS Mojave is reporting expired certificate for downloads.raspberrypi.com

### ISSUE THREAD

**Issue by trejan** [raspberrypi/rpi-imager#661] opened 2023-10-15 14:38 UTC
Had a few reports on the forum about this issue. Raspberry Pi Imager running under Windows works. I can't confirm the bug as I'm not a Mac user but I have checked that the certs are valid.

See https://forums.raspberrypi.com/viewtopic.php?t=357672 and https://forums.raspberrypi.com/viewtopic.php?p=2145006

**Comment by maxnet** [comment] 2023-10-15 18:52
Problem may be that the webserver is sending a LetsEncrypt intermediate certificate for downloads.raspberrypi**.com** that is cross-signed by the DST X3 root certificate that has expired.

Problem may go away if we would switch to the self-signed ISRG Root X1 intermediate certificate from: https://letsencrypt.org/certificates/
But that's up to the server folks (Mythic?)

**Comment by rin67630** [comment] 2023-10-16 06:45
on macOS Mojave, the solution is here:
https://macresearch.org/dst-root-ca-x3-expired-mac/

But, anyhow, the error message on RPI imager **must** mention **which** certifcate is not valid, allowing the user to fix the problem on the source.

**Comment by maxnet** [comment] 2023-10-16 07:15
>on macOS Mojave, the solution is here

Deleting the root certificate on the client can indeed also work.
Not mentioning that certificate server-side (by using the self-signed ISRG Root X1) should also work, and does not require client changes.

>But, anyhow, the error message on RPI imager must mention which certifcate is not valid

Not practical to implement.
Outsources downloads to libcurl, which in turn outsources TLS to various OS specific libraries (openssl or gnutls depending on Linux distribution, yet different system libraries for Windows and Mac OS)
We just pass through the error message received from that, and never get to see the certificate chain ourselves.

**Comment by mudge** [comment] 2023-10-16 09:34
We currently use the default "long" chain handed out by Let's Encrypt but there's a trade-off in compatibility with older software, see https://community.letsencrypt.org/t/long-default-and-short-alternate-certificate-chains-explained/162526

Either way, some clients are going to be incompatible. I raised this with Mythic Beasts but, while switching to the "short" chain may fix this specific error, they are concerned it will introduce more compatibility problems than it fixes.

**Comment by ghollingworth** [comment] 2023-10-16 09:39
Could print out the URL that failed, at least then the user can try the URL in a browser to find out what the issue is?

**Comment by lurch** [comment] 2023-10-16 09:41
Wikipedia https://en.wikipedia.org/wiki/MacOS_Mojave says "Unsupported as of October 2021".

**Comment by maxnet** [comment] 2023-10-16 10:02
>We currently use the default "long" chain handed out by Let's Encrypt but there's a trade-off in compatibility with older 
>software, see https://community.letsencrypt.org/t/long-default-and-short-alternate-certificate-chains-explained/162526

Do ancient Android phones have any business on https://downloads.raspberrypi.com/ ?

**Comment by maxnet** [comment] 2023-10-16 10:05
Alternatively can we change the RPI OS downloads in os_list.json to use downloads.raspberrypi.org instead of .com ?

.org has a proper Sectigo certificate instead of LetsEncrypt.

**Comment by maxnet** [comment] 2023-10-16 10:29
>Wikipedia https://en.wikipedia.org/wiki/MacOS_Mojave says "Unsupported as of October 2021".

Could be.
But market share of OSX users that run something older than Catalina/Big Sur/Monterey is still 8%
https://gs.statcounter.com/os-version-market-share/macos/desktop/worldwide

**Comment by circlinglights** [comment] 2023-10-18 03:35
The error is still occurring for me. I installed the keychain and restarted but no change. Can it not be fixed?

![Raspi SSL Error - Oct_17_2023](https://github.com/raspberrypi/rpi-imager/assets/148303879/c73ae666-ddda-4561-a7a4-eadba814c16b)
![About This Mac](https://github.com/raspberrypi/rpi-imager/assets/148303879/f84cd186-a12c-4746-a8bd-dbc48b133f4a)
![Keychain - ISRG Root X1 - Oct 17 2023](https://github.com/raspberrypi/rpi-imager/assets/148303879/7bae2914-c07d-4cb3-8b1f-c92267b48dcf)

**Comment by maxnet** [comment] 2023-10-18 04:29
Likely need to REMOVE the expired DST certificate from your system, to trick the system. Then it doesn't know the root certificate that is referenced to is expired.

Maybe easier to replace the entire file it is in.
As in download to your home directory: https://curl.se/ca/cacert.pem

Start a terminal:

```
sudo mv /etc/cert/ssl.pem /etc/cert/ssl.backup
sudo mv cacert.pem /etc/cert/ssl.pem
```

**Comment by circlinglights** [comment] 2023-10-18 06:51
I learned in the other thread that I can just download the image itself and select that from the Imager program, and I no longer get the error that way. It's still a workaround but I can get by with it. Thanks, all.

**Comment by nezort11** [comment] 2023-12-08 22:28
**1. Download image from the website**
![image](https://github.com/raspberrypi/rpi-imager/assets/59317431/5553f3bc-7449-4f80-9809-32436148289e)

**2. Use custom image to write**
![image](https://github.com/raspberrypi/rpi-imager/assets/59317431/03e462f3-e477-4911-96ea-953745f17e61)

**Comment by tdewey-rpi** [comment] 2023-12-15 14:27
Closing this issue:

- ISRG Root X1 is valid through 2035, R3 is valid through 2025.
- Mojave is no longer supported by Raspberry Pi Imager (we require 10.15/Catalina at the earliest, and I strongly encourage users to patch their desktop OS').
- There are workarounds for configurations that are not supported in either current macOS or Raspberry Pi Imager

**Closed by tdewey-rpi** 2023-12-15 14:27 UTC
