### ISSUE TITLE
[FEATURE] Add 32-bit to Rasbery Pi (Legacy) image names

### ISSUE THREAD

**Issue by randhid** [raspberrypi/rpi-imager#745] opened 2023-11-29 21:57 UTC
**Is your feature request related to a problem? Please describe.**
It's not explicitly stated that an of the Raspberry Pi Legacy options (for bullseye) is using  32 bit images, while all other options presented with the information on whether they are 32 bit or 64 bit. It is easy for someone to install 32 bit when they meant to try to find the 64 bit image. 

**Describe the solution you'd like**
The imager displays this information for all images, in this sort of fashion:
<img width="656" alt="Screenshot 2023-11-29 at 16 54 55" src="https://github.com/raspberrypi/rpi-imager/assets/35934754/3264d831-160e-401b-99f0-5b36249a5b62">

**Describe alternatives you've considered**
None

**Additional context**

**Comment by lurch** [comment] 2023-11-30 11:21
Duplicate of #722 ?

**Closed** 2023-11-30 11:36 UTC
Labels: enhancement
