### ISSUE TITLE
Config.txt

### ISSUE THREAD

**Issue by jamesbehling** [raspberrypi/rpi-imager#307] opened 2021-11-14 15:31 UTC
My PC
Windows 10
RPI Imager 1.6.2

Steps
Start RPI
Choose OS - Custom - 2021-10-30-raspios-bullseye-arm64-lite.img
Chose Storage - SD Card
Ctrl + Shift + X
This session only
Enable SSH - set password
Enable WIFI - set SSID, set password
Save
Click Write Button

Error Message: 
Unable to customize. File D:/config.txt does not exist

**Comment by lurch** [comment] 2021-11-14 18:00
Duplicate of #289 ?

**Comment by jamesbehling** [comment] 2021-11-14 20:46
Same error message, but different steps.  I was using a custom OS, 64bit plus different advanced configuration.

**Comment by tdewey-rpi** [comment] 2024-02-06 15:03
Closing as duplicate of #289 - different steps still translate into the same failure and likely cause.

**Closed by tdewey-rpi** 2024-02-06 15:03 UTC
