### ISSUE TITLE
Checkbox to enable SSH

### ISSUE THREAD

**Issue by remys** [raspberrypi/rpi-imager#86] opened 2020-07-01 07:39 UTC
When first booting in a Pi, the system will look for a file /boot/ssh, and if found, enable the pi's ssh server.
With the current imager, it is necessary to mount /boot on some computer, and touch this file.
To simplify the setup, please add a check box "enable ssh" on the imager gui

**Comment by lurch** [comment] 2020-07-01 08:06
Duplicate of #25 (amongst others)

**Closed** 2020-11-09 15:32 UTC
