### ISSUE TITLE
Support for multiple SSH pubkeys

### ISSUE THREAD

**Issue by geerlingguy** [raspberrypi/rpi-imager#326] opened 2021-12-20 03:11 UTC
One thing I would like to do sometimes is to add more than one SSH public key to the Pi via imager at a time.

Currently if I go into advanced settings and paste two in (with a newline separating them), they get pasted with a space between the newlines. Then I have to boot the Pi, log into it using the first public key, then edit `~/.ssh/authorized_keys`, and separate the two lines by hand.

It would be a convenience, but understandably not a priority, since I'm probably one of few people who manage multiple SSH keys _and_ do so with a bunch of Pi infrastructure :)

**Comment by maxnet** [comment] 2021-12-20 15:38
Closing this as duplicate of #316
(And recall there is also a somewhat related third issue somewhere with suggestion to allow selection of a file, instead of copy & pasting)

**Closed by maxnet** 2021-12-20 15:38 UTC

**Comment by geerlingguy** [comment] 2021-12-20 15:56
@maxnet ah, based on the title of that other issue I thought it was just someone having trouble with that field. I do see it works, but only for the first key pasted.
