### ISSUE TITLE
Show hint if no suitable storage was found

### ISSUE THREAD

**Issue by serkonda7** [raspberrypi/rpi-imager#482] opened 2022-09-15 10:29 UTC
I open the storage selection but it is empty.
![image](https://user-images.githubusercontent.com/40118727/190381255-f7dd34d6-8785-41e9-ad5e-3bc50f29c731.png)

Does the app still search for devices or has it failed or are none found?
The user cannot tell.

Therefore I suggest showing a message like `No storage found!` if this is the case.

**Comment by lurch** [comment] 2022-09-15 11:35
Duplicate of #321 ?

**Closed** 2022-09-15 12:07 UTC
