### ISSUE TITLE
Headless Set Up doesn't work with any other OS than the default 

### ISSUE THREAD

**Issue by ConstantMan** [raspberrypi/rpi-imager#277] opened 2021-09-15 10:59 UTC
I tried installing Manjaro ARM and Ubuntu ARM  but no matter how many times i do it it never sets up ssh and the password  i set only works for Raspberry OS

I don't know if that's a bug , if I'm doing something wrong, or if it's the intended behavior but if it is please let the users know that for any other OS other than the default they must do the set up manually

rpi-imager from 1.6.2-2 AUR

**Comment by lurch** [comment] 2021-09-15 11:12
Duplicate of #213 ?

**Comment by cillian64** [comment] 2023-10-19 12:45
Closing this as a dupe of #213

**Closed by cillian64** 2023-10-19 12:45 UTC
