### ISSUE TITLE
[Feature Request] Set Static IP addresses via advanced options menu

### ISSUE THREAD

**Issue by earth4s** [raspberrypi/rpi-imager#288] opened 2021-10-13 22:52 UTC
Have an option to be able to set Static IP address in the advanced option menu.

This is a useful feature in headless installs or other embedded situations. Having a pre-assigned IP address takes a lot of the guess work out what the local DHCP assigned the device or if their is not a DHCP implemented on the local network segment.

**Comment by lurch** [comment] 2021-10-13 23:43
Duplicate of #243 ?

**Comment by lurch** [comment] 2021-10-14 11:43
Haha, I found it by searching for "static" :wink: 

> Do you want to close my request or keep it separate?

That's up to @maxnet :man_shrugging:

**Comment by tdewey-rpi** [comment] 2024-02-06 16:17
Closing as a duplicate.

This feature request has been rejected elsewhere because it is unlikely to impact non-technical users, and there's not an immediately obvious way to offer this to non-technical users in a manner that is easily diagnosed and rectified. Use static DHCP leases in a DHCP environment, or a custom-rolled image for more specialised cases.

**Closed by tdewey-rpi** 2024-02-06 16:17 UTC
