### ISSUE TITLE
Is it necessary to remove country code?

### ISSUE THREAD

**Issue by tim-moody** [raspberrypi/rpi-imager#36] opened 2020-03-14 13:51 UTC
A custom image that had country code set and allowed hostapd to run seems to have had that removed when written with rpi-imager. This prevents locale specific images from being duplicated without the extra work of setting country code again.

**Comment by lurch** [comment] 2020-03-14 13:54
Sounds like a duplicate of #35 ?

**Comment by tim-moody** [comment] 2020-03-14 14:03
apples and oranges are both fruit, but are not the same. probably the same philosophy governs both actions. The behavior is the same as what happens when you create an image on rpi 4 and move it to rpi 3. It always works on 4, but hostapd does not start on the 3.

**Comment by ghollingworth** [comment] 2020-03-14 19:04
Again, we do not do any alterations to the original image...  If you can reproduce this with a single image that when written to an SD card with imager gives you a different output to writing it with dd then I'd like to see the image

**Closed by ghollingworth** 2020-03-14 19:04 UTC
