### ISSUE TITLE
[BUG] missing settings when installing ubuntu deskop

### ISSUE THREAD

**Issue by jonnytest1** [raspberrypi/rpi-imager#804] opened 2024-02-06 11:54 UTC
**Describe the bug**
when trying to install "generic oeprating system" > "ubuntu" > "ubuntu dekstop" there is not popup about using custom settings

**To Reproduce**
(1.8.5)
trying to install "generic operating system" > "ubuntu" > "ubuntu dekstop"

**Expected behaviour**
i get a popup asking about wifi credentials and username

**Desktop (please complete the following information):**
 - Windows 11

**The name of the OS you are trying to write**
ubuntu dekstop
**Are you using OS Customisation?**
trying to

**Comment by lurch** [comment] 2024-02-06 12:22
The popup now appears as part of the flashing process, rather than being a separate button in the GUI. See the example walkthrough at https://www.raspberrypi.com/documentation/computers/getting-started.html#raspberry-pi-imager

**Comment by tdewey-rpi** [comment] 2024-02-06 12:23
Closing as this is an intended behaviour.

Canonical appear to have disabled customisation support in their JSON file. Not an issue with rpi-imager.

**Closed by tdewey-rpi** 2024-02-06 12:23 UTC
Labels: bug

**Comment by maxnet** [comment] 2024-02-06 18:19
>Canonical appear to have disabled customisation support in their JSON file. 

They never supported customization on Ubuntu Desktop.
Only Ubuntu server comes with Cloudinit.
