### ISSUE TITLE
WARNING: cgroup v2 is not fully supported yet

### ISSUE THREAD

**Issue by oldviking** [raspberrypi/rpi-imager#146] opened 2021-01-13 21:51 UTC
Add cgroup v2 support. On My Maschine (Fedora 33 latest updaes) otherwise the Application wont anymore. See Screenshot.

![grafik](https://user-images.githubusercontent.com/37188476/104515437-1e60b400-55f3-11eb-9f3a-63d65e18a477.png)

**Comment by maxnet** [comment] 2021-01-13 22:10
You did compile the application from source with "cmake ." -> "make" -> "make install"?

As opposed to using some third-party snap/appimage/flatimage/other-container-technology-of-the-week?

**Comment by oldviking** [comment] 2021-01-13 22:11
Tomorrow I will compile the program, I saw this is a common Problem of snap

**Comment by maxnet** [comment] 2021-01-17 14:58
>Tomorrow I will compile the program, I saw this is a common Problem of snap

Snap problems can be reported here: https://github.com/popey/imager-snap/issues

Closing this.
Reopen if you can reproduce the problem with a normal compile. (Don't think so, because the error talks about confinement and we are not doing any).

**Closed by maxnet** 2021-01-17 14:58 UTC
