### ISSUE TITLE
Backup from SD card?

### ISSUE THREAD

**Issue by cthart** [raspberrypi/rpi-imager#327] opened 2021-12-20 21:35 UTC
Up until now the RPi Imager writes from images to the SD card. How about the other direction? I'd like to be able to clone my SD card. In that case I would like to be able to read from the SD card and write an image, and then subsequently write that image to another SD card.
Useful for backup, but also eg teachers wanting to distribute the same image to a whole classroom.

**Comment by lurch** [comment] 2021-12-21 01:57
Duplicate of e.g. #228

**Closed** 2021-12-21 06:45 UTC
