### ISSUE TITLE
No SD card being displayed for selection

### ISSUE THREAD

**Issue by lrdqs** [raspberrypi/rpi-imager#610] opened 2023-07-17 20:16 UTC
No storage media is displayed after clicking the "Select SD card" button. 

Tried several SD cards, all of which show no abnormalities and are recognized by the system (Manjaro Linux). Also tried uninstalling/reinstalling rpi-imager. Issue occurs with both v1.7.5 and v1.7.4. Worked flawlessly a couple of weeks ago (v1.7.5).

![Screenshot_20230717_2113551](https://github.com/raspberrypi/rpi-imager/assets/85805831/a0309280-747c-496b-aa0c-175172323cd1)

**Comment by lurch** [comment] 2023-07-17 20:22
Is it an internal SD card slot in a laptop? I wonder if this might be similar to #606 ?
Have you got a USB SD card-reader you could try?

**Comment by maxnet** [comment] 2023-07-17 21:46
>Worked flawlessly a couple of weeks ago (v1.7.5).

It seems Arch Linux (and by extension Manjaro, since it uses Arch's packages) did update the util-linux package that provides lsblk, which we use to detect if a drive is removable, 3 weeks ago:

https://archlinux.org/packages/core/x86_64/util-linux/
Last Updated: | 2023-06-27 19:47 UTC

You may want to experiment if it works any better if you downgrade it to a previous version, if you know how, and are  comfortable messing with system packages.

**Comment by lrdqs** [comment] 2023-07-18 16:40
> Is it an internal SD card slot in a laptop?

Yes, I'm on a Dell XPS 15 (7590).

> It seems Arch Linux [...] did update the util-linux package that provides lsblk, which we use to detect if a drive is removable [...]

Good hint, I think that's the culprit. Downgraded and it's working again, so very likely no problem caused by rpi-imager. Thanks for helping!

**Comment by Gusser93** [comment] 2023-08-04 12:47
Here is the [issue](https://github.com/util-linux/util-linux/issues/2379) causing this. Before the `lsblk` update `mmcblk` devices were, per default, considered hotpluggable. But there are soldered eMMC cards in some devices, so this was removed. It was expected, that the kernel announces if the device is hotpluggable. This was not the case, but the [patch](https://lore.kernel.org/lkml/DM6PR04MB657588B4D59F500881051B38FC07A@DM6PR04MB6575.namprd04.prod.outlook.com/) to fix this was submitted and reviewed. (I hope this is an accurate summary of the problem.)
So: No issue of the imager (IMHO) and (probably) soon fixed in the kernel.

**Comment by sudo-splinter-cell** [comment] 2023-10-11 16:15
This issue requires immediate action as the new version of RPI OS was released today and people (like me) who tried to flash it to a new sd card are failing as RPI-Imager can not see any of the sd cards that we are feeding into the usb slots. I understand that this is a linux package update issue but as i understood, it was fixed in the new release of RPI-Imager, however, this version is not in the repo yet. Should't it get an urgent release?

**Comment by ghollingworth** [comment] 2023-10-11 17:36
There's a release in the works

**Comment by MarcoGriep88** [comment] 2023-10-14 17:22
Same issue here: EndeveurOS, rpi-imager for AUR.
linux wlin001 6.5.6-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Oct 2023 08:14:55 +0000 x86_64 GNU/Linux

--enable-writing-system-drives did not work for me. used an external card reader worked.

MSI Prestige 14 A10SC

Best Regards

**Comment by sudo-splinter-cell** [comment] 2023-10-14 18:45
I started to use USBImager instead. It can write to whatever drive you want.

[https://github.com/trollcop/usbimager](url)

**Comment by ghollingworth** [comment] 2023-10-18 15:02
duplicate of #606

**Closed by ghollingworth** 2023-10-18 15:02 UTC
Labels: duplicate

**Comment by calvaris** [comment] 2023-11-14 11:31
I am using debian testing here with util-linux 2.39. Downgrading to 2.38 bypassed this issue.

**Comment by orchard800** [comment] 2023-12-08 08:59
I am also having this issue on Ubuntu 23.10.

**Comment by lurch** [comment] 2023-12-08 13:22
@orchard800 Commenting "I am also having this issue" on an Issue that has already been closed doesn't really add much.
What would be **much** more helpful would be if you could open a new issue, providing all the information that the issue-template asks for, along with any other information that you think might be helpful. Thanks!

**Comment by lurch** [comment] 2024-10-23 10:09
@Megachip Rather than commenting on an issue that was closed over a year ago, could you open a new issue please? Thanks!
You also might want to try the beta v1.9.0 release to see if that works any better? https://github.com/raspberrypi/rpi-imager/releases

**Comment by Megachip** [comment] 2024-10-23 11:38
> Don't expect any help here mate.

I do not expect help, I try to help. 

> @Megachip Rather than commenting on an issue that was closed over a year ago, could you open a new issue please? Thanks! 

Sorry. Most projects have the rule one ticket per bug... so do not open another one for the same bug. In my option this make sense, cause if not, you would have million of issues ;)

> You also might want to try the beta v1.9.0 release to see if that works any better? https://github.com/raspberrypi/rpi-imager/releases

Fixed (if Package is copied to local disk, running directly from image seems not working). Thx

**Comment by lurch** [comment] 2024-10-23 11:45
> I do not expect help, I try to help.

:heart: 

> Most projects have the rule: one ticket per bug... so do not open another one for the same bug.

In most cases I'd tend to agree, but this bug was originally reporting a problem in Imager v1.7.5 and you were reporting a problem in Imager v1.8.5. Also, closed tickets tend to get less attention than still-open tickets.

> Fixed (if Package is copied to local disk, running directly from image seems not working). Thx

Fantastic :tada:  Thanks for confirming.
