### ISSUE TITLE
Imager not saving all settings

### ISSUE THREAD

**Issue by CharlesGodwin** [raspberrypi/rpi-imager#476] opened 2022-08-20 13:20 UTC
V 1.7.2 in windows 10.

If I set this and save settings it works only one time.

Enable SSH" -> "Allow Public key authentication only"

When I use imager again, the setting is always at 
Enable SSH" -> "Use password authentication"

I am expecting the radio button to be sticky and remembered.

**Comment by maxnet** [comment] 2022-08-20 22:14
Duplicate of #464

**Closed by maxnet** 2022-08-20 22:14 UTC
